dist:
  name: otel-collector-with-clickhouse
  description: Custom OpenTelemetry Collector with ClickHouse Exporter
  output_path: ./clickhouse-exporter
  otelcol_version: 0.112.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.112.0
  - gomod: github.com/siAyush/opentelemetry-collector/exporter/clickhouseexporter v0.0.0
    path: ./opentelemetry-collector/exporter/clickhouseexporter

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.112.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.112.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
