receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  clickhouse:
    endpoint: "https://bvahl74qw9.us-east-1.aws.clickhouse.cloud:8443/default?dial_timeout=10s&compress=lz4&secure=true"
    database: "default"
    username: "default"
    password: "_w13iEY0SvURM"
    metrics_table_name: "otel_metrics"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, debug]
  telemetry:
    logs:
      level: debug
